[package]
name = "batt_monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ads1x1x = "0.2.2"
embedded-hal = "0.2.2"
linux-embedded-hal = "0.3"
nb = "1"
paho-mqtt = "0.9"

